"""Bundle the browser modules + sdk/core.js into one file: /sybau.js (works in browsers and Node 18+).

Usage: python tools/build_sdk.py
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PARTS = ["assets/js/brain.js", "assets/js/grammar.js", "assets/js/search.js", "assets/js/pixels.js",
         "assets/js/learn.js", "assets/js/github.js", "assets/js/bot.js"]

head = """/*! sybau.ai SDK - a chatbot that hates you. trained from scratch, runs on your side, no server.
 *  docs: https://osnailcyargta-ctrl.github.io/ai/  (type /connect)
 *  generated by tools/build_sdk.py - edit the files in assets/js and sdk/, not this one.
 */
(function () {
"""
body = []
for p in PARTS:
    src = open(os.path.join(ROOT, p), encoding="utf-8").read()
    # inside the bundle every module attaches to the global object instead of module.exports
    body.append("// ---- " + p + "\n(function (module) {\n" + src + "\n})(undefined);\n")
core = open(os.path.join(ROOT, "sdk", "core.js"), encoding="utf-8").read()
out = head + "\n".join(body) + "\n})();\n// ---- sdk/core.js\n" + core
with open(os.path.join(ROOT, "sybau.js"), "w", encoding="utf-8") as f:
    f.write(out)
print("wrote sybau.js", round(len(out) / 1024), "KB")
